// Auto-generated by scripts/optimize-images.mjs
// Tiny blur placeholders for progressive image loading
// Do not edit manually — regenerate with: node scripts/optimize-images.mjs

export const blurPlaceholders: Record<string, Record<string, string>> = {
  "showcase": {
    "chungkhoan": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAAAwBACdASoUABQAPzmUwVmvKicjqAgB4CcJbACxGwFWAAEbZUP6Ina13wAA5Fv5VS1ZZZVH1hJKxcWP0KBd7kpJGTormGSerX6bmTcEwMHsVi1xuhL4Q8S8xw8vuFe3ZkmyYlaca6sy6CQzHqE0jkSxWfIMnB8AwPShN65kO88vXrEv/gH4gAAA",
    "couple": "data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoUABQAPzmUwVmvKicjqAgB4CcJZAC3uA9mQEaomWy4KsQAAP5gGfMcWLJ/MCDi/wGKP0pT6mtAySGZoOTLXnVD7YibRrRiLGQgbfB7aZN8VkTtGuX4iQAnKpASv7gwdoUXY2yuBehz2MAA",
    "crypto": "data:image/webp;base64,UklGRr4AAABXRUJQVlA4ILIAAADwBACdASoUABQAPzmSv1mvKaYjqAgB4CcJbACdMzQ7KkgAivglxB8hF+NrDusZ2gAA/ujuGhVzs6IkkJ1vrXbo2EXg3wk/rNeAXdtVQ+BMntaB+dq4mYG6uxHNe71K9mF0qYw59M+n+9jFddBCEBqBB3wKB+1dBVejATtKjSVBghHN/ZuCElcUeSqq6Op3fuRJrVSIgzs3d5Oq/OopkmMejHV5F37DzXHcmyN/9bZNAAAA",
    "food": "data:image/webp;base64,UklGRqwAAABXRUJQVlA4IKAAAADQBACdASoUABQAPzmUwFmvKiajqAgB4CcJaACdMxG3WCBt1S730WDZWGPlH3BOlADN3JReoE7t11BpVhtRRH1YnM7adZSJ6YAQYiJqq8nEJv8KuwK+Lhj6m1rUfPbLHG2PpRJmKpZKbeES8PPsUVJRwJzfi6axUVoBQ4B4NFtXXOawkCD9n0SooQX0bltPla0BQF6NhZn3aKsK8GhGGgAA",
    "gaming": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoUABQAPzmUwFmvKiajqAgB4CcJYwDLpA3EtyO0byfI4ncVXlHZkAMAAP7pBls0LNJaFz3+HmAaSPqTCpV1QBeADHEAQehjBk++ZzAQbwrU7NpsItqos+pzJVFhJ7B6XaxgK47OdJkETs3svPq/JEGpjAAAAA==",
    "gym": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAAAQBQCdASoUABQAPzmUwVmvKicjqAgB4CcJZAC/8agSAYYHTBCgOkwJ3NI5bieZPGgAAP5boKVjJNIoG2S9OIHKWXmFtu12A+mU/mKrW5UU4TbD7SuncUjtT9NiF4wt6fQW4eTFtBojHhe6LOGXRXogC92JA8xV3kgLBVfI+Il+k0K8K0ag/9iorETyHd5pIaDEuaQZvwckz+PAAAA=",
    "office": "data:image/webp;base64,UklGRrAAAABXRUJQVlA4IKQAAADQBACdASoUABQAPzmUwFmvKiajqAgB4CcJZgCpCQaAONo2BAm5vDgPPS7334XwAAD+w1T2fHcYMkeE0BByAr1bA+ejCjfWez981R0CKUsxN7/tWczTAPi25X0pBHI49eg0nlnAFvOc2EPEvKGbbfDSj4zNwQLJvtmR+IA2tKB6glTiU8UeQJmttb0WlsXNqhiP7UwwY1oXN1fgda9IBR+5ZXAQAA==",
    "student": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACwAwCdASoUABQAPzmSwFmvKaajqAgB4CcJQBfJAcVRpf7CW36oAADZxR/brqhfpzij6ForHsJ57034bqcGR2uUTHbwWrSaRTu2mbra/t7C+UpDnFWFYDN7W0JRE/pDx035YX5AORHj3s4AAAA="
  },
  "templates": {
    "chibi-cute": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABwBACdASoUABQAPzmEu1avJ6WjsBgIAeAnCWUAACILZjwYniXF3gxghkdqgAD+6pVi6myatLMZR0jhNmcIa8fDXzSI5y4nTKs7M9n3EAXJQ1C9pCTvoDf6oJ9AAAAA",
    "corporate-mascot": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwBACdASoUABQAPzmIvFSvKSYjKA1R4CcJZQDH5BDSXfqzMnv3JHas1VI4AAD+3oU/WaRrEMssTpgx08Pie14qwKok70kybb/rjZyFkvY7ai+2odm0FGORhTKlcY1UyLnKdAQ+t8awqm6UWvGTF8oez4pxwbnxqAAAAA==",
    "flat-vector": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoUABQAPzl+u1QvJ6YjMBgMAeAnCWUAUwADwIt0YgEsqSJJ0LgA/uqMOUaTx67FstNyWO6x/+8eEbMmO7sd3Q31hXMH2uWSD4hl2sKWcL3vS2upLMIEkA77diGmqiWu74AAAA==",
    "graffiti-urban": "data:image/webp;base64,UklGRroAAABXRUJQVlA4IK4AAABQBQCdASoUABQAPzmUwVmvKicjqAgB4CcJQBlAO7lwOm9U4Ngj8lPlAEGtLgm9ABpn8QAA/ufr2n7tmW/OesOx2MuYb1HQ+27ctERrISvsZ/G2WMm9tE/RQGy6jXUtvsa3JihD5ZrsdhKDlWAI9GcUvSS9hz8ZWz34/sO7gfuVMeTUGZlqTFqYyNzfVU7YzrxebOTcIdfslqOYF1gCvoYAIFRdTmAaRBX+D2ElwAA=",
    "manga-anime": "data:image/webp;base64,UklGRpQAAABXRUJQVlA4IIgAAACQBACdASoUABQAPzmSv1mvKaajqAgB4CcJYwAALpmURFxuRHcYKEoysYcDG8AA/up37ncgP2y72pFAgNNJUbXx+y/joa5eHv43AEMaHbl74LNer4cfw+Rbw6oIK9w0tblx6E8eChStmE7ZPOTORwE9x0jD/nUJ/9jqLAz3kZPgdyn4jL0zHAAA",
    "pixel-retro": "data:image/webp;base64,UklGRsoAAABXRUJQVlA4IL4AAAAwBQCdASoUABQAPzmSwFmvKiajqAgB4CcJYwDM0dwLhKKz9NU+P6whS5GTF2edTL7caAD+6pI9wRXrrvw7ySZ0MJpO0u6gLoLVQojD8jSYU5ZozeiJCiC3Thmok8anfLnOhh8GGbGqXkBURs+sEitQhE65h77FqnSzgrzDNzXqbQxh9WsYc/RqtQV2waONUTzT+c/eNNqELqilMRK6hMYK2mNVrVbJE/yHV8IGDLpZxcst3eeC4VF+lChD7wAA",
    "streetwear-flex": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAAAQBACdASoUABQAPzmUwVmvKicjqAgB4CcJQBjege0ybKG6W55/pwPUAAD+5z9a+8+NMKPQjJDYgTJE5gxRS+63pnaa5gNhayCJw8i6g/buBZi9t9SCbq4aSOf1npVoRLMMxhpFbLrAu/3NHfEuaZI1o6d+KskU3uhBCTDZIJGFaAXcYGkQ7A3oRPP8uwAA",
    "watercolor-soft": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQBACdASoUABQAPzmIvFUvKSYjKA1R4CcJYwAALnfL/pglYxCVizHN21XRAAAA/uqJXZtSQqLCKky8wOGE8KKg5lu655UIsAZOAAAA"
  }
} as const;

export function getBlur(category: "showcase" | "templates", name: string): string | undefined {
  return blurPlaceholders[category]?.[name];
}
